---
title: Praktisk AI
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
plugins:
- jekyll-paginate
paginate: 2
paginate_path: "/page:num/"
baseurl: 
description: praktisk.ai - makininlärmning och artificiell intelligens i praktiken!
permalink: pretty
